# =========================
# CONFIG INSTITUCIONAL PRO FINAL
# =========================

CAPITAL_INICIAL = 1000

# Riesgo
RIESGO_POR_TRADE = 0.02
MAX_POSICIONES = 4
MAX_EXPOSICION_TOTAL = 0.6

# Allocation dinámico
PESO_EXCELENTE = 0.30
PESO_BUENO_MIN = 0.15
PESO_BUENO_MAX = 0.20

# Filtros
UMBRAL_COMPRA = 0.80
UMBRAL_EXCELENTE = 1.0
MIN_SCORE = 3

# Gestión
STOP_LOSS = -0.025
TAKE_PROFIT = 0.06

# Control
COOLDOWN = 5
MAX_ENTRADAS_POR_CICLO = 2

# Capital
MIN_CAPITAL_OPERAR = 50
RESERVA_CAPITAL = 0.40