CAPITAL_INICIAL = 1000
USO_CAPITAL = 0.60

MAX_POSICIONES = 3

STOP_LOSS = -0.02
TRAILING_START = 0.02
TRAILING_GAP = 0.015

UMBRAL_EXCELENTE = 0.9
UMBRAL_BUENO = 0.75

MIN_TRADE_USD = 30

COOLDOWN_BASE = 20
CYCLE_TIME = 15

CRYPTOS = [
    "BTC/USDT", "ETH/USDT",
    "SOL/USDT", "AVAX/USDT",
    "ADA/USDT", "XRP/USDT",
    "LINK/USDT", "ATOM/USDT"
]

CORRELACION = {
    "L1": ["BTC/USDT", "ETH/USDT"],
    "L2": ["SOL/USDT", "AVAX/USDT"],
    "L3": ["ADA/USDT", "XRP/USDT"],
    "L4": ["LINK/USDT", "ATOM/USDT"]
}